[[bond]]
source = "tpknam1qzzn5jxtxznp2597qt4gldutf4cqwdtvpcd80dpv0esf45p6kwgajh3ddtl"
validator = "tnam1q8azt2cpqmc6tr2gvg5v62e4jr0t9327yupaf595"
amount = "111"

[bond.signatures]
tpknam1qzzn5jxtxznp2597qt4gldutf4cqwdtvpcd80dpv0esf45p6kwgajh3ddtl =
"signam1qz354tl8465keca2pnm0k83m9f90mwv684ydcrvw9v3lkvvszme5d2sj0ez2lssla7s9cwg3udclpq9ecgfwc33nw6nghw9v6kygq0gqmyjh9p"
